[package]
name = "shell"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
users = "0.11"
terminal_size = "0.3"
tempfile = "3"
ctrlc = "3.4"
iana-time-zone = "0.1.63"

chrono-tz = "0.8"
term_size = "0.3.2"
libc = "0.2.174"


